version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TAG=latest
    image: bnbot:latest
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db/mydatabase
