version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TAG=latest
    image: bnbot:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
      - dynamodb-local
    links:
      - dynamodb-local
    env_file:
      - .env
